plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ivan.moimesta'
    compileSdk 37
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'com.ivan.moimesta'
        minSdk 24
        targetSdk 37
        versionCode 6
        versionName '3.0.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
